public interface MsgType {
    int LOGIN_REQUEST = 1;
    int LOGIN_RESPONSE = 2;
    int USER_LIST = 3;
    int GAME_LIST = 4;
    int NEW_USER = 5;
    int CHAT_NEW_MESSAGE = 6;
    int GAME_NEW = 7;
    int GAME_JOIN_ROOM = 8;
    int GAME_CANCEL_ROOM = 9;
    int GAME_LEAVE_ROOM = 10;
    int GAME_START = 11;
    int TANK_NEW = 12;
    int TANK_MOVE = 13;
    int TANK_DEAD = 14;
    int MISSILE_NEW = 15;
    int MISSILE_DEAD = 16;
    int GAME_QUIT = 17;
    int GAME_END = 18;
    int GAME_LOSER = 19;
    int CLOSE_APP = 20;
}
